[tool.poetry]
name = "json"
version = "0.1.0"
description = ""
authors = ["Teresa Rice <trice@28-7tx.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
